server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  health:
    grpc:
      enabled: false
  

spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    